% Rules generated by tree 4
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,1),
    chol(Patient,X2),
    X2 #=< 201.5.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,1),
    chol(Patient,X2),
    X2 #> 201.5,
    chol(Patient,X3),
    X3 #=< 234.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,1),
    chol(Patient,X2),
    X2 #> 201.5,
    chol(Patient,X3),
    X3 #> 234.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,1),
    age(Patient,X3),
    X3 #=< 61.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,1),
    age(Patient,X3),
    X3 #> 61.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,2),
    thal(Patient,2).

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,2),
    thal(Patient,3).

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,2),
    fbs(Patient,0).

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,2),
    fbs(Patient,1).

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #=< 1.65.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #> 1.65.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,2),
    oldpeak(Patient,X3),
    X3 #=< 0.3.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,2),
    oldpeak(Patient,X3),
    X3 #> 0.3.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #=< 0.7.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #> 0.7.

