% Rules generated by tree 3
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #=< 157.0,
    restecg(Patient,0).

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #=< 157.0,
    restecg(Patient,1).

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #> 157.0,
    thal(Patient,1).

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #> 157.0,
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,0),
    thalach(Patient,X3),
    X3 #=< 144.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,0),
    thalach(Patient,X3),
    X3 #> 144.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,1),
    thalach(Patient,X3),
    X3 #=< 152.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,1),
    thalach(Patient,X3),
    X3 #> 152.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,2),
    thalach(Patient,X3),
    X3 #=< 125.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,2),
    thalach(Patient,X3),
    X3 #> 125.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,3),
    trestbps(Patient,X3),
    X3 #=< 110.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,3),
    trestbps(Patient,X3),
    X3 #> 110.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    restecg(Patient,0),
    age(Patient,X3),
    X3 #=< 61.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    restecg(Patient,0),
    age(Patient,X3),
    X3 #> 61.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    restecg(Patient,1).

