% Rules generated by tree 0
% ---------------------------------------------

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 3.55,
    chol(Patient,X3),
    X3 #=< 154.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 3.55,
    chol(Patient,X3),
    X3 #> 154.5.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 3.55.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,0),
    thalach(Patient,X3),
    X3 #=< 160.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,0),
    thalach(Patient,X3),
    X3 #> 160.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,1),
    chol(Patient,X3),
    X3 #=< 151.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,1),
    chol(Patient,X3),
    X3 #> 151.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 0.8,
    chol(Patient,X3),
    X3 #=< 236.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 0.8,
    chol(Patient,X3),
    X3 #> 236.5.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 0.8,
    trestbps(Patient,X3),
    X3 #=< 135.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 0.8,
    trestbps(Patient,X3),
    X3 #> 135.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,2),
    thalach(Patient,X2),
    X2 #=< 170.0,
    chol(Patient,X3),
    X3 #=< 202.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,2),
    thalach(Patient,X2),
    X2 #=< 170.0,
    chol(Patient,X3),
    X3 #> 202.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,2),
    thalach(Patient,X2),
    X2 #> 170.0.

