% Examples and explainability in Prolog format
% ------------------------------------------------------


% Rules from diagnosis_1.pl:
% Rules generated by tree 0
% ---------------------------------------------

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 3.55,
    chol(Patient,X3),
    X3 #=< 154.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 3.55,
    chol(Patient,X3),
    X3 #> 154.5.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 3.55.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,0),
    thalach(Patient,X3),
    X3 #=< 160.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,0),
    thalach(Patient,X3),
    X3 #> 160.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,1),
    chol(Patient,X3),
    X3 #=< 151.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,0),
    thal(Patient,2),
    ca(Patient,1),
    chol(Patient,X3),
    X3 #> 151.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 0.8,
    chol(Patient,X3),
    X3 #=< 236.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 0.8,
    chol(Patient,X3),
    X3 #> 236.5.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 0.8,
    trestbps(Patient,X3),
    X3 #=< 135.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 0.8,
    trestbps(Patient,X3),
    X3 #> 135.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,2),
    thalach(Patient,X2),
    X2 #=< 170.0,
    chol(Patient,X3),
    X3 #=< 202.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,2),
    thalach(Patient,X2),
    X2 #=< 170.0,
    chol(Patient,X3),
    X3 #> 202.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    exang(Patient,1),
    thal(Patient,2),
    thalach(Patient,X2),
    X2 #> 170.0.


% Rules from diagnosis_2.pl:
% Rules generated by tree 1
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,0),
    trestbps(Patient,X2),
    X2 #=< 151.0,
    sex(Patient,0).

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,0),
    trestbps(Patient,X2),
    X2 #=< 151.0,
    sex(Patient,1).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,0),
    trestbps(Patient,X2),
    X2 #> 151.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,2),
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,2),
    thal(Patient,3).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,3),
    ca(Patient,0).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,3),
    ca(Patient,1).

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,0),
    age(Patient,X3),
    X3 #=< 61.5.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,0),
    age(Patient,X3),
    X3 #> 61.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,1),
    age(Patient,X3),
    X3 #=< 63.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,1),
    age(Patient,X3),
    X3 #> 63.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,2),
    chol(Patient,X3),
    X3 #=< 242.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,2),
    chol(Patient,X3),
    X3 #> 242.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,3),
    chol(Patient,X3),
    X3 #=< 301.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,3),
    chol(Patient,X3),
    X3 #> 301.5.


% Rules from diagnosis_3.pl:
% Rules generated by tree 2
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #=< 148.0,
    slope(Patient,0).

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #=< 148.0,
    slope(Patient,1).

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #> 148.0,
    oldpeak(Patient,X3),
    X3 #=< 2.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #> 148.0,
    oldpeak(Patient,X3),
    X3 #> 2.5.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #=< 273.0,
    age(Patient,X3),
    X3 #=< 51.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #=< 273.0,
    age(Patient,X3),
    X3 #> 51.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #> 273.0,
    oldpeak(Patient,X3),
    X3 #=< 2.7.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #> 273.0,
    oldpeak(Patient,X3),
    X3 #> 2.7.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #=< 122.5,
    thalach(Patient,X3),
    X3 #=< 155.0.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #=< 122.5,
    thalach(Patient,X3),
    X3 #> 155.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #> 122.5,
    age(Patient,X3),
    X3 #=< 65.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #> 122.5,
    age(Patient,X3),
    X3 #> 65.0.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,2),
    trestbps(Patient,X3),
    X3 #=< 112.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,2),
    trestbps(Patient,X3),
    X3 #> 112.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,3),
    exang(Patient,0).

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,3),
    exang(Patient,1).


% Rules from diagnosis_4.pl:
% Rules generated by tree 3
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #=< 157.0,
    restecg(Patient,0).

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #=< 157.0,
    restecg(Patient,1).

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #> 157.0,
    thal(Patient,1).

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #> 157.0,
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,0),
    thalach(Patient,X3),
    X3 #=< 144.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,0),
    thalach(Patient,X3),
    X3 #> 144.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,1),
    thalach(Patient,X3),
    X3 #=< 152.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,0),
    thal(Patient,3),
    exang(Patient,1),
    thalach(Patient,X3),
    X3 #> 152.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,2),
    thalach(Patient,X3),
    X3 #=< 125.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,2),
    thalach(Patient,X3),
    X3 #> 125.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,3),
    trestbps(Patient,X3),
    X3 #=< 110.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    cp(Patient,3),
    trestbps(Patient,X3),
    X3 #> 110.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    restecg(Patient,0),
    age(Patient,X3),
    X3 #=< 61.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    restecg(Patient,0),
    age(Patient,X3),
    X3 #> 61.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    ca(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    restecg(Patient,1).


% Rules from diagnosis_5.pl:
% Rules generated by tree 4
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,1),
    chol(Patient,X2),
    X2 #=< 201.5.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,1),
    chol(Patient,X2),
    X2 #> 201.5,
    chol(Patient,X3),
    X3 #=< 234.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,1),
    chol(Patient,X2),
    X2 #> 201.5,
    chol(Patient,X3),
    X3 #> 234.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,1),
    age(Patient,X3),
    X3 #=< 61.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,1),
    age(Patient,X3),
    X3 #> 61.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,2),
    thal(Patient,2).

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,0),
    restecg(Patient,2),
    ca(Patient,2),
    thal(Patient,3).

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,2),
    fbs(Patient,0).

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,2),
    fbs(Patient,1).

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #=< 1.65.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,2),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #> 1.65.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,2),
    oldpeak(Patient,X3),
    X3 #=< 0.3.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,2),
    oldpeak(Patient,X3),
    X3 #> 0.3.

diagnosis(Patient,0,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #=< 0.7.

diagnosis(Patient,1,'Dra. Taylor') :- 
    slope(Patient,1),
    thal(Patient,3),
    cp(Patient,3),
    oldpeak(Patient,X3),
    X3 #> 0.7.


% Rules from diagnosis_6.pl:
% Rules generated by tree 5
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 1.95,
    slope(Patient,0),
    ca(Patient,2).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 1.95,
    slope(Patient,0),
    ca(Patient,3).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 1.95,
    slope(Patient,1),
    fbs(Patient,0).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 1.95,
    slope(Patient,1),
    fbs(Patient,1).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 1.95,
    thalach(Patient,X2),
    X2 #=< 166.5,
    chol(Patient,X3),
    X3 #=< 269.5.

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 1.95,
    thalach(Patient,X2),
    X2 #=< 166.5,
    chol(Patient,X3),
    X3 #> 269.5.

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 1.95,
    thalach(Patient,X2),
    X2 #> 166.5,
    exang(Patient,0).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 1.95,
    thalach(Patient,X2),
    X2 #> 166.5,
    exang(Patient,1).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #=< 151.0,
    thal(Patient,2),
    chol(Patient,X3),
    X3 #=< 232.5.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #=< 151.0,
    thal(Patient,2),
    chol(Patient,X3),
    X3 #> 232.5.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #=< 151.0,
    thal(Patient,3).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #> 151.0,
    age(Patient,X2),
    X2 #=< 59.5,
    ca(Patient,0).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #> 151.0,
    age(Patient,X2),
    X2 #=< 59.5,
    ca(Patient,1).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #> 151.0,
    age(Patient,X2),
    X2 #> 59.5,
    age(Patient,X3),
    X3 #=< 63.5.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    thalach(Patient,X1),
    X1 #> 151.0,
    age(Patient,X2),
    X2 #> 59.5,
    age(Patient,X3),
    X3 #> 63.5.


% Consult from consult.pl:
?- findall(diagnosis(Z,Y,X), diagnosis(Z, Y, X), List).
% Explainability information from explainability.pl:
#pred findall(X, Y, Z) :: 'All done'.

#pred diagnosis(X,1,Y) :: '@(Y) said that @(X) is at the gates of heaven'.
#pred diagnosis(X,0,Y) :: '@(Y)  said that @(X) is fresh like a daisy'.

#pred age(X, Age) :: 'is @(Age) years old'.

#pred sex(X, 1) :: 'is male'.
#pred sex(X, 0) :: 'is female'.

#pred cp(X, 0) :: 'has typical angina'.
#pred cp(X, 1) :: 'has atypical angina'.
#pred cp(X, 2) :: 'has non-anginal pain'.
#pred cp(X, 3) :: 'is asymptomatic'.

#pred trestbps(X, BP) :: 'has a resting blood pressure of @(BP) mm/HG'.

#pred chol(X, Chol) :: 'has a cholesterol level of @(Chol) mg/dl'.

#pred fbs(X, 1) :: 'has a high fasting blood sugar level'.
#pred fbs(X, 0) :: 'has a normal fasting blood sugar level'.

#pred restecg(X, 0) :: 'has a normal resting ECG result'.
#pred restecg(X, 1) :: 'has an ST-T wave abnormality in the resting ECG result'.
#pred restecg(X, 2) :: 'has left ventricular hypertrophy in the resting ECG result'.

#pred thalach(X, HR) :: 'has a maximum heart rate of @(HR)'.

#pred exang(X, 1) :: 'has exercise-induced angina'.
#pred exang(X, 0) :: 'hasn`t exercise-induced angina'.

#pred oldpeak(X, Depression) :: 'has exercise-induced ST depression of @(Depression)'.

#pred slope(X, 0) :: 'has an upsloping ST segment during peak exercise'.
#pred slope(X, 1) :: 'has a flat ST segment during peak exercise'.
#pred slope(X, 2) :: 'has a downsloping ST segment during peak exercise'.

#pred ca(X, Vessels) :: 'has @(Vessels) major vessels'.

#pred thal(X, 1) :: 'has normal blood flow'.
#pred thal(X, 2) :: 'has a fixed defect'.
#pred thal(X, 3) :: 'has a reversible defect'.




