% Rules generated by tree 2
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #=< 148.0,
    slope(Patient,0).

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #=< 148.0,
    slope(Patient,1).

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #> 148.0,
    oldpeak(Patient,X3),
    X3 #=< 2.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,2),
    thalach(Patient,X2),
    X2 #> 148.0,
    oldpeak(Patient,X3),
    X3 #> 2.5.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #=< 273.0,
    age(Patient,X3),
    X3 #=< 51.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #=< 273.0,
    age(Patient,X3),
    X3 #> 51.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #> 273.0,
    oldpeak(Patient,X3),
    X3 #=< 2.7.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    cp(Patient,3),
    chol(Patient,X2),
    X2 #> 273.0,
    oldpeak(Patient,X3),
    X3 #> 2.7.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #=< 122.5,
    thalach(Patient,X3),
    X3 #=< 155.0.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #=< 122.5,
    thalach(Patient,X3),
    X3 #> 155.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #> 122.5,
    age(Patient,X3),
    X3 #=< 65.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.9,
    trestbps(Patient,X2),
    X2 #> 122.5,
    age(Patient,X3),
    X3 #> 65.0.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,2),
    trestbps(Patient,X3),
    X3 #=< 112.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,2),
    trestbps(Patient,X3),
    X3 #> 112.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,3),
    exang(Patient,0).

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.9,
    thal(Patient,3),
    exang(Patient,1).

