% Rules generated by tree 1
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,0),
    trestbps(Patient,X2),
    X2 #=< 151.0,
    sex(Patient,0).

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,0),
    trestbps(Patient,X2),
    X2 #=< 151.0,
    sex(Patient,1).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,0),
    trestbps(Patient,X2),
    X2 #> 151.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,2),
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,2),
    thal(Patient,3).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,3),
    ca(Patient,0).

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #=< 57.5,
    slope(Patient,1),
    cp(Patient,3),
    ca(Patient,1).

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,0),
    age(Patient,X3),
    X3 #=< 61.5.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,0),
    age(Patient,X3),
    X3 #> 61.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,1),
    age(Patient,X3),
    X3 #=< 63.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,0),
    exang(Patient,1),
    age(Patient,X3),
    X3 #> 63.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,2),
    chol(Patient,X3),
    X3 #=< 242.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,2),
    chol(Patient,X3),
    X3 #> 242.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,3),
    chol(Patient,X3),
    X3 #=< 301.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    age(Patient,X0),
    X0 #> 57.5,
    ca(Patient,1),
    cp(Patient,3),
    chol(Patient,X3),
    X3 #> 301.5.

