% Examples, rules, and explainability in Prolog format
% ------------------------------------------------------

% Examples:
% Examples:
age(patientGenerated, 1).
sex(patientGenerated, 1).
cp(patientGenerated, 1).
trestbps(patientGenerated, 1).
chol(patientGenerated, 1).
fbs(patientGenerated, 1).
restecg(patientGenerated, 1).
thalach(patientGenerated, 1).
exang(patientGenerated, 1).
oldpeak(patientGenerated, 1).
slope(patientGenerated, 1).
ca(patientGenerated, 1).
thal(patientGenerated, 1).
target(patientGenerated, 1).

% Rules from rules_with_explainability.pl:
% Examples and explainability in Prolog format
% ------------------------------------------------------


% Rules from diagnosis_1.pl:
% Rules generated by tree 0
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,1),
    age(Patient,X2),
    X2 #=< 56.5,
    age(Patient,X3),
    X3 #=< 50.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,1),
    age(Patient,X2),
    X2 #=< 56.5,
    age(Patient,X3),
    X3 #> 50.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,1),
    age(Patient,X2),
    X2 #> 56.5,
    fbs(Patient,0).

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,1),
    age(Patient,X2),
    X2 #> 56.5,
    fbs(Patient,1).

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,2),
    thalach(Patient,X2),
    X2 #=< 173.0,
    chol(Patient,X3),
    X3 #=< 301.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,2),
    thalach(Patient,X2),
    X2 #=< 173.0,
    chol(Patient,X3),
    X3 #> 301.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #=< 0.85,
    ca(Patient,2),
    thalach(Patient,X2),
    X2 #> 173.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,1),
    chol(Patient,X2),
    X2 #=< 259.5,
    exang(Patient,0).

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,1),
    chol(Patient,X2),
    X2 #=< 259.5,
    exang(Patient,1).

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,1),
    chol(Patient,X2),
    X2 #> 259.5,
    chol(Patient,X3),
    X3 #=< 290.0.

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,1),
    chol(Patient,X2),
    X2 #> 259.5,
    chol(Patient,X3),
    X3 #> 290.0.

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #=< 151.0,
    cp(Patient,2).

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #=< 151.0,
    cp(Patient,3).

diagnosis(Patient,1,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #> 151.0,
    chol(Patient,X3),
    X3 #=< 293.5.

diagnosis(Patient,0,'Dr. Smith') :- 
    oldpeak(Patient,X0),
    X0 #> 0.85,
    thal(Patient,2),
    trestbps(Patient,X2),
    X2 #> 151.0,
    chol(Patient,X3),
    X3 #> 293.5.


% Rules from diagnosis_2.pl:
% Rules generated by tree 1
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    thalach(Patient,X2),
    X2 #=< 141.0,
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    thalach(Patient,X2),
    X2 #=< 141.0,
    thal(Patient,3).

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    thalach(Patient,X2),
    X2 #> 141.0,
    ca(Patient,0).

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    thalach(Patient,X2),
    X2 #> 141.0,
    ca(Patient,1).

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    trestbps(Patient,X2),
    X2 #=< 122.5.

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    trestbps(Patient,X2),
    X2 #> 122.5,
    chol(Patient,X3),
    X3 #=< 228.0.

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    trestbps(Patient,X2),
    X2 #> 122.5,
    chol(Patient,X3),
    X3 #> 228.0.

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,0),
    chol(Patient,X2),
    X2 #=< 217.5,
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,0),
    chol(Patient,X2),
    X2 #=< 217.5,
    thal(Patient,3).

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,0),
    chol(Patient,X2),
    X2 #> 217.5,
    chol(Patient,X3),
    X3 #=< 254.5.

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,0),
    chol(Patient,X2),
    X2 #> 217.5,
    chol(Patient,X3),
    X3 #> 254.5.

diagnosis(Patient,0,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,1),
    age(Patient,X2),
    X2 #=< 46.5,
    thal(Patient,1).

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,1),
    age(Patient,X2),
    X2 #=< 46.5,
    thal(Patient,2).

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,1),
    age(Patient,X2),
    X2 #> 46.5,
    chol(Patient,X3),
    X3 #=< 298.0.

diagnosis(Patient,1,'Dr. Johnson') :- 
    cp(Patient,3),
    slope(Patient,1),
    age(Patient,X2),
    X2 #> 46.5,
    chol(Patient,X3),
    X3 #> 298.0.


% Rules from diagnosis_3.pl:
% Rules generated by tree 2
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #=< 57.5,
    chol(Patient,X2),
    X2 #=< 235.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #=< 57.5,
    chol(Patient,X2),
    X2 #> 235.5,
    trestbps(Patient,X3),
    X3 #=< 113.5.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #=< 57.5,
    chol(Patient,X2),
    X2 #> 235.5,
    trestbps(Patient,X3),
    X3 #> 113.5.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #> 57.5,
    trestbps(Patient,X2),
    X2 #=< 122.0,
    sex(Patient,0).

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #> 57.5,
    trestbps(Patient,X2),
    X2 #=< 122.0,
    sex(Patient,1).

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #> 57.5,
    trestbps(Patient,X2),
    X2 #> 122.0,
    ca(Patient,0).

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,1),
    age(Patient,X1),
    X1 #> 57.5,
    trestbps(Patient,X2),
    X2 #> 122.0,
    ca(Patient,1).

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    restecg(Patient,1),
    age(Patient,X3),
    X3 #=< 66.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    restecg(Patient,1),
    age(Patient,X3),
    X3 #> 66.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    restecg(Patient,2),
    thalach(Patient,X3),
    X3 #=< 180.5.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 0.55,
    restecg(Patient,2),
    thalach(Patient,X3),
    X3 #> 180.5.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    trestbps(Patient,X2),
    X2 #=< 131.0,
    thalach(Patient,X3),
    X3 #=< 145.0.

diagnosis(Patient,0,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    trestbps(Patient,X2),
    X2 #=< 131.0,
    thalach(Patient,X3),
    X3 #> 145.0.

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    trestbps(Patient,X2),
    X2 #> 131.0,
    exang(Patient,0).

diagnosis(Patient,1,'Dra. Lee') :- 
    thal(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 0.55,
    trestbps(Patient,X2),
    X2 #> 131.0,
    exang(Patient,1).


% Rules from diagnosis_4.pl:
% Rules generated by tree 3
% ---------------------------------------------

diagnosis(Patient,0,'Dr. Brown') :- 
    restecg(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 1.15,
    thalach(Patient,X2),
    X2 #=< 168.5,
    ca(Patient,1).

diagnosis(Patient,1,'Dr. Brown') :- 
    restecg(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 1.15,
    thalach(Patient,X2),
    X2 #=< 168.5,
    ca(Patient,2).

diagnosis(Patient,0,'Dr. Brown') :- 
    restecg(Patient,1),
    oldpeak(Patient,X1),
    X1 #=< 1.15,
    thalach(Patient,X2),
    X2 #> 168.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    restecg(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 1.15,
    thal(Patient,1),
    age(Patient,X3),
    X3 #=< 59.0.

diagnosis(Patient,0,'Dr. Brown') :- 
    restecg(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 1.15,
    thal(Patient,1),
    age(Patient,X3),
    X3 #> 59.0.

diagnosis(Patient,1,'Dr. Brown') :- 
    restecg(Patient,1),
    oldpeak(Patient,X1),
    X1 #> 1.15,
    thal(Patient,2).

diagnosis(Patient,0,'Dr. Brown') :- 
    restecg(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 2.35,
    ca(Patient,0),
    chol(Patient,X3),
    X3 #=< 268.5.

diagnosis(Patient,1,'Dr. Brown') :- 
    restecg(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 2.35,
    ca(Patient,0),
    chol(Patient,X3),
    X3 #> 268.5.

diagnosis(Patient,0,'Dr. Brown') :- 
    restecg(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 2.35,
    ca(Patient,1),
    sex(Patient,0).

diagnosis(Patient,1,'Dr. Brown') :- 
    restecg(Patient,2),
    oldpeak(Patient,X1),
    X1 #=< 2.35,
    ca(Patient,1),
    sex(Patient,1).

diagnosis(Patient,1,'Dr. Brown') :- 
    restecg(Patient,2),
    oldpeak(Patient,X1),
    X1 #> 2.35.


% Rules from diagnosis_5.pl:
% Rules generated by tree 4
% ---------------------------------------------

diagnosis(Patient,1,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,0),
    slope(Patient,0),
    age(Patient,X3),
    X3 #=< 50.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,0),
    slope(Patient,0),
    age(Patient,X3),
    X3 #> 50.5.

diagnosis(Patient,1,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,0),
    slope(Patient,1),
    age(Patient,X3),
    X3 #=< 63.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,0),
    slope(Patient,1),
    age(Patient,X3),
    X3 #> 63.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 1.9,
    trestbps(Patient,X3),
    X3 #=< 111.0.

diagnosis(Patient,1,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,1),
    oldpeak(Patient,X2),
    X2 #=< 1.9,
    trestbps(Patient,X3),
    X3 #> 111.0.

diagnosis(Patient,1,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #=< 147.5,
    exang(Patient,1),
    oldpeak(Patient,X2),
    X2 #> 1.9.

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #> 147.5,
    oldpeak(Patient,X1),
    X1 #=< 2.45,
    restecg(Patient,1),
    cp(Patient,2).

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #> 147.5,
    oldpeak(Patient,X1),
    X1 #=< 2.45,
    restecg(Patient,1),
    cp(Patient,3).

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #> 147.5,
    oldpeak(Patient,X1),
    X1 #=< 2.45,
    restecg(Patient,2),
    thalach(Patient,X3),
    X3 #=< 192.5.

diagnosis(Patient,1,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #> 147.5,
    oldpeak(Patient,X1),
    X1 #=< 2.45,
    restecg(Patient,2),
    thalach(Patient,X3),
    X3 #> 192.5.

diagnosis(Patient,0,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #> 147.5,
    oldpeak(Patient,X1),
    X1 #> 2.45,
    age(Patient,X2),
    X2 #=< 51.5.

diagnosis(Patient,1,'Dra. Taylor') :- 
    thalach(Patient,X0),
    X0 #> 147.5,
    oldpeak(Patient,X1),
    X1 #> 2.45,
    age(Patient,X2),
    X2 #> 51.5.


% Rules from diagnosis_6.pl:
% Rules generated by tree 5
% ---------------------------------------------

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    slope(Patient,1),
    thal(Patient,2).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    slope(Patient,1),
    thal(Patient,3).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    slope(Patient,2),
    cp(Patient,1).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #=< 55.5,
    slope(Patient,2),
    cp(Patient,2).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    oldpeak(Patient,X2),
    X2 #=< 2.0,
    cp(Patient,1).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    oldpeak(Patient,X2),
    X2 #=< 2.0,
    cp(Patient,2).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    oldpeak(Patient,X2),
    X2 #> 2.0,
    cp(Patient,1).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,2),
    age(Patient,X1),
    X1 #> 55.5,
    oldpeak(Patient,X2),
    X2 #> 2.0,
    cp(Patient,2).

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,0),
    exang(Patient,0),
    trestbps(Patient,X3),
    X3 #=< 145.0.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,0),
    exang(Patient,0),
    trestbps(Patient,X3),
    X3 #> 145.0.

diagnosis(Patient,0,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,0),
    exang(Patient,1),
    slope(Patient,0).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,0),
    exang(Patient,1),
    slope(Patient,1).

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,1),
    thalach(Patient,X2),
    X2 #=< 123.0,
    age(Patient,X3),
    X3 #=< 63.0.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,1),
    thalach(Patient,X2),
    X2 #=< 123.0,
    age(Patient,X3),
    X3 #> 63.0.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,1),
    thalach(Patient,X2),
    X2 #> 123.0,
    oldpeak(Patient,X3),
    X3 #=< 0.15.

diagnosis(Patient,1,'Dra. Davis') :- 
    cp(Patient,3),
    ca(Patient,1),
    thalach(Patient,X2),
    X2 #> 123.0,
    oldpeak(Patient,X3),
    X3 #> 0.15.


% Consult from consult.pl:
?- findall(diagnosis(Z,Y,X), diagnosis(Z, Y, X), List).
% Explainability information from explainability.pl:
#pred findall(X, Y, Z) :: 'All done'.

#pred diagnosis(X,1,Y) :: '@(Y) said that @(X) is at the gates of heaven'.
#pred diagnosis(X,0,Y) :: '@(Y)  said that @(X) is fresh like a daisy'.

#pred age(X, Age) :: 'has @(Age) years old'.

#pred sex(X, 1) :: 'is male'.
#pred sex(X, 0) :: 'is female'.

#pred cp(X, 0) :: 'has typical angina'.
#pred cp(X, 1) :: 'has atypical angina'.
#pred cp(X, 2) :: 'has non-anginal pain'.
#pred cp(X, 3) :: 'is asymptomatic'.

#pred trestbps(X, BP) :: 'has a resting blood pressure of @(BP) mm/HG'.

#pred chol(X, Chol) :: 'has a cholesterol level of @(Chol) mg/dl'.

#pred fbs(X, 1) :: 'has a high fasting blood sugar level'.
#pred fbs(X, 0) :: 'has a normal fasting blood sugar level'.

#pred restecg(X, 0) :: 'has a normal resting ECG result'.
#pred restecg(X, 1) :: 'has an ST-T wave abnormality in the resting ECG result'.
#pred restecg(X, 2) :: 'has left ventricular hypertrophy in the resting ECG result'.

#pred thalach(X, HR) :: 'has a maximum heart rate of @(HR)'.

#pred exang(X, 1) :: 'has exercise-induced angina: yes'.
#pred exang(X, 0) :: 'has exercise-induced angina: no'.

#pred oldpeak(X, Depression) :: 'has exercise-induced ST depression of @(Depression)'.

#pred slope(X, 0) :: 'has an upsloping ST segment during peak exercise'.
#pred slope(X, 1) :: 'has a flat ST segment during peak exercise'.
#pred slope(X, 2) :: 'has a downsloping ST segment during peak exercise'.

#pred ca(X, Vessels) :: 'has @(Vessels) major vessels'.

#pred thal(X, 1) :: 'has normal blood flow'.
#pred thal(X, 2) :: 'has a fixed defect'.
#pred thal(X, 3) :: 'has a reversible defect'.





% Consult from consult.pl:
?- findall(diagnosis(Z,Y,X), diagnosis(Z, Y, X), List).
% Explainability information from explainability.pl:
#pred findall(X, Y, Z) :: 'All done'.

#pred diagnosis(X,1,Y) :: '@(Y) said that @(X) is at the gates of heaven'.
#pred diagnosis(X,0,Y) :: '@(Y)  said that @(X) is fresh like a daisy'.

#pred age(X, Age) :: 'is @(Age) years old'.

#pred sex(X, 1) :: 'is male'.
#pred sex(X, 0) :: 'is female'.

#pred cp(X, 0) :: 'has typical angina'.
#pred cp(X, 1) :: 'has atypical angina'.
#pred cp(X, 2) :: 'has non-anginal pain'.
#pred cp(X, 3) :: 'is asymptomatic'.

#pred trestbps(X, BP) :: 'has a resting blood pressure of @(BP) mm/HG'.

#pred chol(X, Chol) :: 'has a cholesterol level of @(Chol) mg/dl'.

#pred fbs(X, 1) :: 'has a high fasting blood sugar level'.
#pred fbs(X, 0) :: 'has a normal fasting blood sugar level'.

#pred restecg(X, 0) :: 'has a normal resting ECG result'.
#pred restecg(X, 1) :: 'has an ST-T wave abnormality in the resting ECG result'.
#pred restecg(X, 2) :: 'has left ventricular hypertrophy in the resting ECG result'.

#pred thalach(X, HR) :: 'has a maximum heart rate of @(HR)'.

#pred exang(X, 1) :: 'has exercise-induced angina'.
#pred exang(X, 0) :: 'hasn`t exercise-induced angina'.

#pred oldpeak(X, Depression) :: 'has exercise-induced ST depression of @(Depression)'.

#pred slope(X, 0) :: 'has an upsloping ST segment during peak exercise'.
#pred slope(X, 1) :: 'has a flat ST segment during peak exercise'.
#pred slope(X, 2) :: 'has a downsloping ST segment during peak exercise'.

#pred ca(X, Vessels) :: 'has @(Vessels) major vessels'.

#pred thal(X, 1) :: 'has normal blood flow'.
#pred thal(X, 2) :: 'has a fixed defect'.
#pred thal(X, 3) :: 'has a reversible defect'.




